# Generated by Django 5.0.4 on 2024-06-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
